name: development

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: echo 'no test :('

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1

      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build debug flavor development
        run: flutter build apk --debug --flavor development --target lib/main_development.dart
